AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ExternalId:
    Description: Insert the External ID you got from Anodot
    Type: String

  RootOUId:
    Type: String
    Description: ID of Organization Root OU
    Default: 'empty'

Resources:

  LinkedAccountsOrganizationalUnit:
    Type: AWS::Organizations::OrganizationalUnit
    Properties:
      Name: AnodotLinkedAccounts
      ParentId: !Ref RootOUId

  ChildAccountsStackSet:
    Type: AWS::CloudFormation::StackSet
    DeletionPolicy: Retain
    Properties:
      Capabilities:
        - CAPABILITY_NAMED_IAM
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds:
              - !GetAtt LinkedAccountsOrganizationalUnit.Id
          Regions:
            - us-east-1
      AutoDeployment:
        Enabled: True
        RetainStacksOnAccountRemoval: False
      StackSetName: AnodotLinkedAccountRole
      Description: Deploys Anodot Role to all linked accounts in Organization
      PermissionModel: SERVICE_MANAGED
      TemplateURL: !Sub https://pileus-cloudformation-public.s3.amazonaws.com/PileuseOnboardingCFT.json
      Parameters:
        - ParameterKey: ExternalId
          ParameterValue: !Ref ExternalId
