name: Pull Reqeust Checks

on:
  pull_request:
    paths:
      - '**.yaml'
      - '**.yml'
jobs:
  validate:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cfn-lint

      - name: Validate CloudFormation templates
        run: |
          cfn-lint aws/*.yaml aws-linked/*.yaml || true